server:
  port: 5555
  #ssl:
    #key-store: classpath:htx-server.jks
    #key-store-password: '!QAZ2wsx'
    #key-store-type: PKCS12
    #key-alias: tomcat
  
spring:
  application:
    name: hobart-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/     # 集群配置
  instance:
    instance-id: hobart-gateway-001
    prefer-ip-address: true
    
zuul:
  host:
    max-total-connections: 200    #总连接数
    max-per-route-connections: 20   #每个路由连接数
  prefix: /hubo
  ignored-services: "*"
  routes: 
#    user-route.serviceId: hobart-provider-user
#    user-route.path: /myuser/**
#    user-route.url: http://localhost:6001/
    user-route: 
      path: /user/*
      service-id: hobart-provider-user
    shop-route: 
      path: /shop/**
      service-id: hobart-provider-shop
      
