server:
  port: 6002
  
spring:
  application:
    name: hobart-provider-shop
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/     # 集群配置
  instance:
    instance-id: hobart-provider-shop
    prefer-ip-address: true