server:
  port: 8003
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路劲
  type-aliases-package: com.hobart.test.base.model      # 所有Entity别名类所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                   # mapper映射文件
  
spring:
  application:
    name: hobart-test-dept
  sleuth: 
    sampler:
      percentage: 0.1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/hobartTestDB03     # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                       # 数据库连接池的最小维持连接数
      initial-size: 5                                   # 初始化连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200                              # 等待连接获取的最大超时时间
  rabbitmq: 
    port: 5672
    username: hubo
    password: 123456
    host: 192.168.123.102
      
eureka:
  client:   # 客户端注册进Eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka/     # 单机配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/     # 集群配置
  instance:
    instance-id: hobart-test-dept8003   # 注册服务列表的别名
    prefer-ip-address: true             # 访问路劲可以显示IP地址
    
info:       # 服务列表服务信息
  app.name: hubo-hobartcloud
  company.name: www.hubo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$